spring.application.name=demo
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
server.address=0.0.0.0
server.port=8080
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false
